name: Create Release

on:
  workflow_dispatch:

jobs:
  create-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get next version
      uses: reecetech/version-increment@2023.4.1
      id: version
      with:
        scheme: semver
        increment: patch
    - name: Create tag
      run: git tag ${{ steps.version.outputs.version }}
    - name: Create GH Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
