name: Update PSL

on:
  schedule:
    - cron: "0 0 */3 * *" # At 00:00 on every 3rd day-of-month.
  workflow_dispatch:

jobs:
  update-psl:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update PSL
      run: python update-psl.py
    - name: Create pull request to commit updated psl
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Update PSL
        title: '[Automatic] Update PSL'
